name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2b90f9b508d24759b9614c5bd6faf2bc14d2c767312e88a28122d646415e4b4"

[versions]
minecraft = "1.19.2"
quilt = "0.22.1-beta.4"
