name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a7ec374024f7af0f3e1fbc9a82c75dcf2e77db7595dafeaf6ae6d5266e3350e"

[versions]
minecraft = "1.19.2"
quilt = "0.22.1-beta.4"
