name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd80977a06f8b477c5390f2279f2688854d40f7492db764fcc6b79839d93ab0c"

[versions]
minecraft = "1.19.2"
quilt = "0.23.0"
