name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81c5c145dc250d1497af10afac21d7bd908303ec3fe941a608710981ad9a482b"

[versions]
minecraft = "1.19.2"
quilt = "0.22.1-beta.4"
