name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce41a23461ad2c40e9797338df8346db5d546dc73bde98c71fa02ea06bec04ad"

[versions]
minecraft = "1.19.2"
quilt = "0.23.0"
