name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67288ba9669c061f4515d65bb32942532de799a7fb58ae9699d018df3683aeca"

[versions]
minecraft = "1.19.2"
quilt = "0.22.1-beta.4"
