name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44aded4f589a7bc1dea4fdaeb403d04f89505b1aaa69b0cb4e4525e608a28bfb"

[versions]
minecraft = "1.19.2"
quilt = "0.23.0"
