name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f69860d6fe809373630c677a4924e65bb9cefa83ef05f5455cbdf0eff7239a6a"

[versions]
minecraft = "1.19.2"
quilt = "0.22.1-beta.4"
