name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f0a01f6d1b59fd1d63efc526c06c46533d48bbc072888d0c18affa5986aa5f8"

[versions]
minecraft = "1.19.2"
quilt = "0.22.1-beta.4"
