name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17d9fa6255f890ff114c23d2f5f07c216564495f7d6b352ccb33a8d3fb3d9a35"

[versions]
minecraft = "1.19.2"
quilt = "0.22.1-beta.4"
