name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03adacdd59930f6612038ea9e3727b746be13dece242e88ff08bee20300dcda4"

[versions]
minecraft = "1.19.2"
quilt = "0.23.0"
