name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54322ac9f325270c2521c5f8635fec58941dcdfff63c1e94b2c6420c9fce19b0"

[versions]
minecraft = "1.19.2"
quilt = "0.23.0"
