name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0fc4a6912533a755419add1f15c8c0704e6863502623b09aa3c660d586ce931"

[versions]
minecraft = "1.19.2"
quilt = "0.23.0"
