name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c2857aa0d084fbde74eaf257aea3fe1f85c1939c8fd3955da6e5f5d4f8b3390"

[versions]
minecraft = "1.19.2"
quilt = "0.22.1-beta.4"
