name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a5145ccee7041de9390105c03c7c2f7bbee814779258e3a0d371ce4ccad9240"

[versions]
minecraft = "1.19.2"
quilt = "0.22.1-beta.4"
