name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e7c622b2ed275370d711b89d83a7f30e2bd082dc2e495ab8bf345639dd2b2f5"

[versions]
minecraft = "1.19.2"
quilt = "0.22.1-beta.4"
