name = "Bitbox Reloaded"
author = "Violet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc03d9244929a99458aee14e312bb58820d7e025c7248ba56578b0a11206d4bb"

[versions]
minecraft = "1.19.2"
quilt = "0.22.1-beta.4"
